# This is a SendToFlinkPregel Config File

"kafka": {
  "topic": "kafka"
  "kafkaBootStrapServers": "localhost:9092"
  "dateFormat": "yyyy-MM-dd'T'HH:mm:ss.SSS"
  "nodeFilePath": "node_blogel_reachability_3window.csv"
  "scenarioFilePath": "scenario_blogel_reachability_3window.csv"
}
