# This is a SendToFlinkPregel Config File

"kafka": {
  "topic": "max4"
  "kafkaBootStrapServers": "localhost:9092"
  "dateFormat": "yyyy-MM-dd'T'HH:mm:ss.SSS"
  "gzipFile": "cnr-2000.jsonl.gz"
}


#"kafka": {
#  "topic": "definetopic"
#  "kafkaBootStrapServers": "defineBootStrapServers"
#  "dateFormat": "---"
#  "nodeFilePath": "nodeFileUnknown"
#  "scenarioFilePath": "scenarioFileUnknown"
#}